---
- hosts: gitlabservers
  become: yes
  vars_files:
    - vars/gitlab.yml
  roles:
     - { role: deploy-gitlab, tags: ["deploy-gitlab"] }
     - { role: undeploy-gitlab, tags: ["undeploy-gitlab"] }

- hosts: jenkinsservers
  become: yes
  vars_files:
    - vars/jenkins.yml
  roles:
     - { role: deploy-jenkins, tags: ["deploy-jenkins"] }
     - { role: undeploy-jenkins, tags: ["undeploy-jenkins"] }